version: '3.8'
name: "csc8113-bookstore-backend"

services:
  catalog-service:
    image: paritosh4495/csc8113bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/catalog_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:9191/realms/mylabs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9191/realms/mylabs/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m


  cart-service:
    image: paritosh4495/csc8113bookstore-cart-service
    container_name: cart-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CART_CATALOG_SERVICE_URL=http://catalog-service:8081
      - DB_URL=jdbc:postgresql://cart-db:5432/cart_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:9191/realms/mylabs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9191/realms/mylabs/protocol/openid-connect/certs
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      cart-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m


  api-gateway:
    image: paritosh4495/csc8113bookstore-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - CART_SERVICE_URL=http://cart-service:8082
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:9191/realms/mylabs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9191/realms/mylabs/protocol/openid-connect/certs
    ports:
      - "9000:9000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m