---
# The Service: Opens port 8082 on the internal K8s network
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 8082
      targetPort: 8082

---
# The Deployment: Manages the Cart Service Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: paritosh4495/csc8113bookstore-cart-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: CART_CATALOG_SERVICE_URL
              value: "http://catalog-service:8081" # Points to the internal K8s Catalog Service
            - name: DB_URL
              value: "jdbc:postgresql://postgres-db:5432/cart"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://localhost:9191/realms/mylabs"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:9191/realms/mylabs/protocol/openid-connect/certs"
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "700Mi"