apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: postgres
  password: CloudComputingGroupProjectGroup1

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  admin-password: CloudComputingGroupProjectGroup1
