name: Cart Service CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - backend/cart-service/**
  pull_request:
    branches:
      - main
    paths:
      - backend/cart-service/**

jobs:

  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/cart-service
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: |
          chmod +x ../mvnw
          ../mvnw -ntp verify

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: ./backend/cart-service
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/csc8113bookstore-cart-service
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          COMMIT_HASH=${GITHUB_SHA:0:7}
          ../mvnw spring-boot:build-image -DskipTests -DdockerImageName=${{ env.DOCKER_IMAGE_NAME }}:$COMMIT_HASH
          docker push ${{ env.DOCKER_IMAGE_NAME }}:$COMMIT_HASH
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:$COMMIT_HASH ${{ env.DOCKER_IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      - name: Rollout restart
        run: |
          kubectl rollout restart deployment/cart-service
          kubectl rollout status deployment/cart-service
